version: '3.9'
services:
   db:
    image: postgres:14-alpine3.16
    restart: unless-stopped
    user: postgres:postgres
    env_file:
      - .env
    container_name: "${PROJECT_NAME:-demo}_db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_USER: "${DB_USER:-admin}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-admin}"
      POSTGRES_DB: "${DB_DATABASE:-demo}"
    # volumes:
    #   - ./volumes/pgdata:/var/lib/postgresql/data
