# File: docker-compose.yml
# Access via "http://localhost:8081"
#
# Call example:
# $ docker-compose up

version: '3.9'
networks:
  inside:
    external: false
services:
  db:
    image: postgres:${PGSQL_VERSION:-10-alpine3.16}
    restart: unless-stopped
    # env_file:
    #   - .env
    container_name: "${PROJECT_NAME:-default}_ojs_db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_USER: "${DB_USER:-admin}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-admin}"
      POSTGRES_DB: "${DB_DATABASE:-default}"
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
      - ../scripts/sql/dbojssajhom_2022-04-27_bkp_pedidoSAJ.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - inside
  ojs:
    env_file:
      - .env
    image: incolume/ojs:${OJS_VERSION:-3_2_1-4}_${OS_APP_NAME:-alpine3.11}
    build:
      context: ojs
      args:
        OS_APP_BASE: ${OS_APP_BASE:-alpine:3.11}
        OJS_VERSION: ${OJS_VERSION:-3_2_1-4}
        PHP_ENGINE: ${PHP_ENGINE:-php7}
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
    environment:
#      PHP_ENGINE: ${PHP_ENGINE:-php7}
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
    restart: unless-stopped
    container_name: "${PROJECT_NAME:-default}_ojs_app"
    hostname: "${PROJECT_NAME:-default}"
    ports:
      - "${HTTP_PORT:-8081}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - ../volumes/rjp_hom/arquivos_ojssaj:/var/www/files
      - ../volumes/rjp_hom/ojs-3.2.1-4/public:/var/www/html/public
      - ./ojs/config/config.inc.php:/var/www/html/config.inc.php

    networks:
      - inside
    depends_on:
      - db
